# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'XJWeibo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 0.30.0.beta2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'SVProgressHUD', '~> 2.0.3'
  # Pods for XJWeibo

  target 'XJWeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XJWeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
